Added social Links  in  footer
DeFiCh/scan pull request #123
Opened 2021-08-05 08:05 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Social media links on footer
#### Which issue(s) does this PR fixes?:

Fixes #94 

#### Additional comments?:

### Screenshot

<img width="376" alt="image" src="https://user-images.githubusercontent.com/57817584/128314592-d34f255c-ed67-473d-91c9-8834e9fd8e64.png">

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/57817584/128314688-0da1c646-99ff-464d-a236-659956f4b6bd.png">

2021-08-05 08:28 UTC, fuxingloh requested changes

2021-08-05 08:28 UTC, fuxingloh commented on src/layouts/components/Footer.tsx
> +                <FaTwitterSquare size={25} />
```suggestion
                <FaTwitterSquare size={24} />
```

Always try to use even numbers due to down/up scale algorithm where odd multiple won't look as favorable due to 2x, 3x screens

2021-08-05 08:28 UTC, fuxingloh commented on src/layouts/components/Footer.tsx
> +            <div className='flex flex-wrap mt-3  w-84'>
Extract this part out into a JSX function `FooterSocialLink` and put it below.

2021-08-05 09:14 UTC, siradji commented
@aikchun

2021-08-05 12:19 UTC, siradji commented
@fuxing all changes are done.

2021-08-06 05:22 UTC, fuxingloh approved these changes
- I refactored the remaining sections into function as well. 
- Also refactored my Sitemap to follow your sizing on socials. 
- Additionally, I dropped the use of `md:flex-row flex-col` breakpoint should control overflow not orientetation. 
- I also updated some styles due to recent design changes from Jon

2021-08-06 05:22 UTC, merged