fix(ui-ux): fixed search box issue of hide on off click
DeFiCh/scan pull request #1257
Opened 2022-06-16 11:00 UTC by fullstackninja864

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #845

#### Sample Links & Screenshots:

Link: 
<details>
<summary>Desktop Screenshot</summary>

</details>
<details>
<summary>Mobile Screenshot</summary>

</details>

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on multiple web browsers
- [ ] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [ ] No console errors
- [ ] Unit tests*
- [ ] Added e2e tests*

2022-06-17 07:21 UTC, thedoublejay requested changes
When tabbing on a search result, it goes to that page. It should only go on enter

2022-06-17 10:19 UTC, kyleleow commented
There is a regression in behaviour, e.g.:
- type a valid transaction address in the field `2930ccff93e4d524e07dfbeb05725ac71db0461e3aec3501fbbef54a229de96f`
- the search result appears at the bottom (correct)
- click anywhere outside of the search field
- search result disappear (correct)
- mouse click into search input field
- in the current PROD the search result would appear again, but in the PR, it never does

2022-06-20 09:33 UTC, kyleleow commented
Let's make the search box at the top right to have the same behaviour too. Currently takes two click to dismiss the search result box
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40191153/174572145-90178082-a842-4d99-9780-dee8a05bd4fb.png">

2022-06-21 02:33 UTC, kyleleow approved these changes

2022-06-21 08:12 UTC, kyleleow approved these changes

2022-06-21 08:12 UTC, merged