Appended ID to DST tokens name
DeFiCh/scan pull request #253
Opened 2021-09-07 12:08 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
 Append ID to DST tokens to avoid confusion 
#### Which issue(s) does this PR fixes?:

Fixes #247 

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on multiple web browsers
- [ ] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [ ] No console errors
- [ ] Unit tests*
- [ ] Added e2e tests*

2021-09-07 12:16 UTC, monstrobishi approved these changes

2021-09-07 12:17 UTC, monstrobishi requested changes
Actually we might as well change it in the main heading of the tokens/:id page too

2021-09-07 12:27 UTC, siradji commented
> Actually we might as well change it in the main heading of the tokens/:id page too

It is done!

2021-09-07 12:31 UTC, monstrobishi submitted a review, later dismissed

2021-09-08 04:35 UTC, fuxingloh approved these changes

2021-09-08 04:36 UTC, fuxingloh approved these changes

2021-09-08 04:41 UTC, merged