Updated Defi dex logo
DeFiCh/scan pull request #278
Opened 2021-09-14 18:54 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Changed defi dex logo to match recent design
#### Which issue(s) does this PR fixes?:

Fixes #277

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on multiple web browsers
- [x] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [x] No console errors
- [x] Unit tests*
- [x] Added e2e tests*

2021-09-15 02:27 UTC, jtlntno-cake requested changes
Logos' sizes and alignments appear inconsistent and misaligned – this is due to varied image treatments of the logo files used. 

To solve this, i've tweaked the logos' sizes to have them in consistent frames and the necessary margins within them. Please see attached file
[Price feeds - logos 09:15:2021.zip](https://github.com/DeFiCh/scan/files/7166251/Price.feeds.-.logos.09.15.2021.zip)

PNGs are provided with each logo having the intended margins.

They should appear like in this image
![Screen Shot 2021-09-15 at 10 19 58 AM](https://user-images.githubusercontent.com/85162376/133359817-488a668a-90dd-4580-97d6-38e3ae5a0877.png)

You can also inspect the sizes in [this Figma link](https://www.figma.com/file/XyC92lfHtuASf2IU3o0dho/DeFiScan?node-id=218%3A23096)

Ideally, this makes the logos sizes appear consistently.

2021-09-15 20:22 UTC, siradji commented
@jtlntno-cake , have made the changes accordingly. Please check and let me know your thoughts.

2021-09-16 03:30 UTC, jtlntno-cake approved these changes

2021-09-16 03:31 UTC, jtlntno-cake commented
Looks better and cleaner. Thanks @siradji

2021-09-16 04:11 UTC, merged