Tokens page with e2e
DeFiCh/scan pull request #81
Opened 2021-07-28 00:52 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Rought implementation of tokens page  with E2E
#### Which issue(s) does this PR fixes?:

Fixes #45 

#### Additional comments?:

2021-07-29 08:25 UTC, fuxingloh requested changes

2021-07-29 08:25 UTC, fuxingloh commented on src/interfaces/index.ts
> +export interface TokenData {
access this interface from the package

```ts
import { tokens } from '@defichain/whale-api-client'

tokens.TokenData
```

2021-07-29 08:25 UTC, fuxingloh commented on src/components/shared/Loader.tsx
> +export const Loader = (): JSX.Element => {
https://github.com/DeFiCh/scan/blob/main/CONTRIBUTING.md#top-level-functions-should-not-use-arrow-syntax

2021-07-29 08:25 UTC, fuxingloh commented on src/components/shared/index.ts
> +export * from './Loader'
don't need to use and maintain `index.ts` since this is not a library project.

2021-07-29 08:26 UTC, fuxingloh commented on src/pages/tokens.tsx
> +  const rpc = useWhaleApiClient()
```suggestion
  const api = useWhaleApiClient()
```

2021-07-29 14:47 UTC, canonbrother commented on src/pages/tokens.tsx
> +      // NOTE(siradji) Made 2 the default query size. Will be changing it when design is finalized.
```suggestion
      // NOTE(siradji): Made 2 the default query size. Will be changing it when design is finalized.
```

2021-07-29 14:50 UTC, canonbrother commented on src/pages/tokens.tsx
> +    setTokens(response as any)
hmm... i think we have proper type, instead of any, can you ensure it?

2021-07-29 14:51 UTC, canonbrother reviewed
minor requirement.. can you screenshot the token page?
eg: https://github.com/DeFiCh/scan/pull/62

update:
ohh.. just aware cypress does the screenshot

2021-08-10 09:44 UTC, fuxingloh commented
Drop all changes that isn't part of `/tokens`.

2021-08-10 09:46 UTC, fuxingloh commented
Also create another PR from main instead, this branch is too stale.

2021-08-10 10:47 UTC, closed without merging